  const i18n = {
  en: {
    nicknames: {
      ambitious_tywin: 'aywin ml.tywin mltywin',
      angelic_montmorancy: 'momo',
      arbiter_vildred: 'arby',
      assassin_cartuja: 'fatcat',
      assassin_cidd: 'a.cidd accid',
      assassin_coli: 'a.coli acoli',
      auxiliary_lots: 'a.lots alots',
      benevolent_romann: 'broman',
      blood_blade_karin: 'bbk',
      challenger_dominiel: 'c.dom cdom',
      champion_zerato: 'c.zerato czerato',
      church_of_ilryos_axe: 'axe god axegod',
      crescent_moon_rin: 'ml.rin mlrin',
      crimson_armin: 'c.armin carmin',
      dark_corvus: 'dc DC',
      desert_jewel_basar: 'dj.basar djbasar',
      faithless_lidica: 'f.lidica flidica',
      falconer_kluri: 'f.kluri fkluri',
      fallen_cecilia: 'f.cc fcc',
      fighter_maya: 'f.maya fmaya',
      general_purrgis: 'g.purrgis gpurrgis',
      holiday_yufine: 'hufine',
      jack_o: 'jacko',
      judge_kise: 'j.kise jkise',
      maid_chloe: 'ml.chloe mlchloe',
      martial_artist_ken: 'ml.ken mlken',
      mort: 'mortelix',
      sage_baal_and_sezan: 'ml.baal mlbaal',
      shooting_star_achates: 'ssa',
      seaside_bellona: 'ssb',
      silver_blade_aramintha: 'ml.aramintha mlaramintha',
      sinful_angelica: 'ml.angelica mlangelica',
      specimen_sez: 'ml.sez mlsez',
      specter_tenebria: 'specte ml.tenebria mltenebria',
      taranor_guard: 'tg',
      troublemaker_crozet: 'ml.crozet mlcrozet',
      wanderer_silk: 'ml.silk mlsilk',
    },
    skills: {
      mods: 'Skill Modifiers',
      att_rate: 'Attack Rate',
      power: 'Power',
      mult: 'Mult Mod',
      flat: 'Flat Mod',
      critBoost: 'Crit Dmg',
      pen: 'Penetrate',
      detonation: 'Detonation',
      exEq: 'Excl. Equipment',
      elemAdv: 'Elemental Adv',
      afterMathFormula: 'Aftermath',
      afterMathDmg: 'Aftermath Dmg',
      extraDmg: 'Extra Dmg',
      fixed: 'Fixed Dmg',
      custom: {
        caster_target_atk_diff: '{v}% Attack Difference',
        caster_target_spd_diff: '{v}% Speed Difference',
        caster_target_def_diff: '{v}% Def Difference',
        all_fire: '{v}% Team Fire',
        allies_buff: '+{v} per Buff',
        caster_defense: '{v}% Defense',
        caster_left_hp_pc: '{v}% remaining HP%',
        caster_lost_hp: '{v}% lost HP',
        caster_lost_hp_pc: '{v}% lost HP%',
        caster_max_hp: '{v}% max HP',
        caster_hp_pc_over_hp_threshold: '{v}% HP% [above threshold]',
        caster_rage: '{v}% Rage',
        caster_speed: '{v}% Speed',
        caster_hp_pc_under_hp_threshold: '{v}% HP% [below threshold]',
        caster_vs_target_hp_diff: 'Caster vs Target HP Diff: {v}%/1000hp',
        dead_people: '{v}% per dead hero',
        elemental_advantage: '{v}% Elem. Adv.',
        per_crit_hit: '{v}% per Critical Hit',
        per_target: '{v}% per Target',
        per_bleed: '{v}% per Bleed',
        per_fewer_target: '{v}% per fewer Target',
        per_focus: '{v}% per Focus',
        per_stack: '{v}% per Stack',
        per_target_debuff: '{v}% per Debuff',
        skill_tree: 'Skill Tree: {v}%',
        target_bleed: 'Target Bleed: {v}%',
        target_debuff: 'Target Debuff: {v}%',
        target_has_buff: 'Target has Buff: {v}%',
        target_has_debuff: 'Target has Debuff: {v}%',
        target_has_barrier: 'Target has Barrier: {v}%',
        target_has_no_buff: 'Target has no Buff: {v}%',
        target_lost_hp_pc: '{v}% Target lost HP%',
        target_magic_nail: 'Magic Nail: {v}%',
        target_max_hp: '{v}% Target max HP',
        target_speed: '{v}% Target Speed',
        under_threshold: 'Below Threshold: {v}%',
      }
    },
    info: {
      alencia_trample: 'Trample',
      aria_scaling: 'Heads up: Crit Damage scaling out of lost HP% is probably wrong. Skill multipliers are accurate.',
      balance_op_sigret: 'Balance Update: Added Speed scaling, lowered Attack scaling: S2: 0.8 -> 0.75 / S3 1.1 -> 1',
      lqc_s3_splash: 'S3 Splash',
      ml_celine_nimble_sword: 'Nimble Sword',
      run: '暴走(计算心理阴影伤害时修改攻击力加成到100%-300%)',
      run_soulburn: '暴走烧魂(计算心理阴影伤害时修改攻击力加成到100%-300%)',
      s1_extra_attack: 'S1 Extra Attack',
      s1_soulburn: 'S1 烧魂',
      s2_wave_2: 'S2 Wave 2',
      s2_counter: 'S2 (Counter)',
      s2_wave_3: 'S2 Wave 3',
      sez_explosion: 'Explosion',
      victorious_flag: 'Elemental advantage must be enabled to see benefits from this artifact; doesn\'t apply to light and dark heroes',
      yoonryoung_slash: 'Dazzling Slash'
    }
  },
  zhCN: {
    heroes: {
      achates: '雅卡泰丝',
      adin: '艾庭',
      adlay: '亚迪赖',
      adventurer_ras: '冒险家拉斯',
      ainos: '艾诺斯',
      ains: '艾因兹',
      aither: '埃德勒',
      alencia: '艾莲西雅',
      alexa: '雅莉莎',
      all_rounder_wanda: '疑难杂症专家汪达',
      ambitious_tywin: '野心份子泰温',
      angel_of_light_angelica: '光之天使安洁莉卡',
      angelic_montmorancy: '守护天使蒙茉朗西',
      angelica: '安洁莉卡',
      apocalypse_ravi: '末日萝菲',
      aramintha: '雅拉敏塔',
      arbiter_vildred: '执行官维德瑞',
      archdemon_shadow: '魔神的暗影',
      aria: '艾莉雅',
      armin: '亚敏',
      arowell: '小光盾(未转职)',
      assassin_cartuja: '杀手卡尔图哈',
      assassin_cidd: '杀手席德',
      assassin_coli: '杀手可丽',
      auxiliary_lots: '辅助型拉兹',
      azalea: '亚洁理亚',
      baal_and_sezan: '巴尔&塞尚',
      bad_cat_armin: '坏坏猫亚敏',
      baiken: '梅喧',
      basar: '巴萨尔',
      bask: '巴思克',
      batisse: '巴托斯',
      belian: '伯里安',
      bellona: '维尔萝娜',
      benevolent_romann: '仁慈的洛曼',
      blaze_dingo: '烈火汀果',
      blood_blade_karin: '血剑卡琳',
      blood_moon_haste: '赤月的贵族海斯特',
      briar_witch_iseria: '灰光森林的伊赛丽亚',
      butcher_corps_inquisitor: '混沌教屠杀追击者',
      camilla: '卡米拉',
      captain_rikoris: '先锋队长里科黎司',
      carmainerose: '卡麦萝兹',
      carrot: '卡萝',
      cartuja: '卡尔图哈',
      cecilia: '赛西莉亚',
      celeste: '赛雷斯特',
      celestial_mercedes: '外太空的玫勒赛德丝',
      celine: '瑟琳',
      cerise: '赛瑞丝',
      cermia: '洁若米亚',
      challenger_dominiel: '挑战者多米妮尔',
      champion_zerato: '终结者杰拉图',
      chaos_inquisitor: '屠杀部队员',
      chaos_sect_axe: '混沌教巨斧大将军',
      charles: '查尔斯',
      charlotte: '夏绿蒂',
      chloe: '克萝爱',
      choux: '小泡芙',
      christy: '克莉丝媞',
      church_of_ilryos_axe: '伊利欧斯教斧兵',
      cidd: '席德',
      clarissa: '克莱莉莎',
      closer_charles: '末日指挥官查尔斯',
      coli: '可丽',
      commander_lorina: '指挥官萝里娜',
      commander_model_laika: '指挥型莱伊卡',
      commander_pavel: '司令官帕贝尔',
      conqueror_lilias: '支配者莉莉亚斯',
      corvus: '科尔布思',
      crescent_moon_rin: '新月舞姬铃儿',
      crimson_armin: '红焰亚敏',
      crozet: '克罗泽',
      dark_corvus: '黑暗的科尔布思',
      desert_jewel_basar: '沙漠宝石巴萨尔',
      designer_lilibet: '设计师莉莉贝',
      destina: '戴丝蒂娜',
      diene: '迪埃妮',
      dingo: '汀果',
      dizzy: '蒂姬',
      doll_maker_pearlhorizon: '制偶师波萝莱珍',
      dominiel: '多米妮尔',
      doris: '朵莉思',
      eaton: '伊顿',
      eda:'艾妲',
      edward_elric: '爱德华·爱力克',
      elena: '艾蕾娜',
      elphelt_valentine: '爱尔菲特',
      elson: '艾尔森',
      emilia:'爱蜜莉雅',
      enott: '艾诺特',
      ervalen: '艾尔巴伦',
      fairytale_tenebria: '童话泰妮布里雅',
      faithless_lidica: '无神论者丽迪卡',
      falconer_kluri: '鹰猎人可露莉',
      fallen_cecilia: '堕落的赛西莉亚',
      fighter_maya: '战斗型玛雅',
      flan: '芙兰',
      free_spirit_tieria: '永恆不变的黛莉亚',
      furious: '尤贝乌斯',
      general_purrgis: '大将法济斯',
      glenn: '格伦',
      gloomyrain: '格鲁美兰',
      godmother: '教母',
      great_chief_khawana: '大族长卡瓦娜',     
      guider_aither: '求道者埃德勒',
      gunther: '坤特',
      haste: '海斯特',
      hasol: '夏率',
      hataan: '哈坦',
      hazel: '海兹',
      helen: '海伦',
      helga: '赫尔嘉',
      holiday_yufine: '度假风优芬妮',
      holy_flame_adin: '圣炎的艾庭',
      hurado: '修拉杜',
      hwayoung: '和英',
      ian: '伊安',
      ilynav: '伊莉娜芙',
      inferno_khawazu: '烈焰的卡瓦朱',
      iseria: '伊赛丽亚',
      jack_o: '杰克·欧',
      januta: '扎努塔',
      jecht: '杰克托',
      jena: '捷娜',
      judge_kise: '审判者绮世',
      judith: '茱迪丝',
      kanna: '暴击型卡农',
      karin: '卡琳',
      kawerik: '卡威利',
      kayron: '凯隆',
      ken: '肯恩',
      khawana: '卡瓦娜',
      khawazu: '卡瓦朱',
      kikirat_v2: '奇奇拉特V.2',
      kiris: '奇丽丝',
      kise: '绮世',
      kitty_clarissa: '猫咪克莱莉莎',
      kizuna_ai: '绊爱',
      kluri: '可露莉',
      krau: '克劳乌',
      landy: '兰蒂',
      last_rider_krau:'最后的骑士克劳乌',
      lena: '雷娜',
      leo: '雷欧',
      lidica: '丽迪卡',
      lilias: '莉莉亚斯',
      lilibet: '莉莉贝',
      lionheart_cermia: '狮心王洁若米亚',
      little_queen_charlotte: '年轻的女王夏绿蒂',
      lorina: '萝里娜',
      lots: '拉兹',
      lucy: '露西',
      ludwig: '鲁特比',
      luluca: '璐璐卡',
      luna: '露娜',
      magic_scholar_doris: '魔法学者朵莉思',
      maid_chloe: '仆人克萝爱',
      martial_artist_ken: '武斗家肯恩',
      mascot_hazel: '吉祥物海兹',
      maya: '玛雅',
      mediator_kawerik: '协调者卡威利',
      melany: '玫拉妮',
      melissa: '梅丽莎',
      mercedes: '玫勒赛德丝',
      mercenary_helga: '自由自在的佣兵赫尔嘉',
      mighty_scout: '侦察兵玛伊堤',
      milim: '米莉姆',
      mirsa: '米勒莎',
      mistychain: '美丝缇彩',
      montmorancy: '蒙茉朗西',
      moon_bunny_dominiel: '月兔多米妮尔',
      mort:'魔勒',
      mucacha: '穆卡察',
      mui:'缪伊',
      muse_rima: '缪斯黎玛',
      muwi: '武蔚',
      nemunas: '尼姆拉斯',
      operator_sigret: '操作员赛珂兰特',
      orte: '奥乐缇',
      otillie: '奥缇莉尔',
      pavel: '帕贝尔',
      pearlhorizon: '波萝莱珍',
      peira: '沛伊拉',
      penelope: '潘尼罗佩',
      pirate_captain_flan: '海盗船长芙兰',
      politis: '佛里蒂丝',
      purrgis: '法济斯',
      pyllis: '费莉丝',
      ram:'拉姆',
      ran: '岚',
      ras: '拉斯',
      ravi: '萝菲',
      ray: '雷伊',
      rem:'雷姆',
      remnant_violet: '残影的菲奥雷托',
      requiemroar: '雷奎姆洛',
      researcher_carrot: '研究者卡萝',
      righteous_thief_roozid: '义贼鲁兹德',
      rikoris: '里科黎司',
      rima: '黎玛',
      rimuru: '利姆路',
      rin: '铃儿',
      riza_hawkeye: '莉莎·霍克爱',
      roaming_warrior_leo: '流浪勇士雷欧',
      roana: '罗安纳',
      romann: '洛曼',
      roozid: '鲁兹德',
      rose: '萝季',
      roy_mustang: '罗伊·马斯坦古',
      ruele_of_light: '光之瑞儿',
      sage_baal_and_sezan: '贤者巴尔&塞尚',
      schuri: '修里',
      seaside_bellona: '海边的维尔萝娜',
      senya:'赛娜',
      serila: '塞丽拉',
      sez: '赛兹',
      shadow_knight_pyllis: '黑骑士费莉丝',
      sharun: '莎伦',
      shadow_rose: '暗影萝季',
      shooting_star_achates: '流星雅卡泰丝',
      shuna: '朱菜',
      sigret: '赛珂兰特',
      silk: '席可',
      silver_blade_aramintha: '白银刀刃的雅拉敏塔',
      sinful_angelica: '罪戾的安洁莉卡',
      sol: '索尔',
      solitaria_of_the_snow: '雪国的苏莉塔妮亚',
      sonia: '苏尼娅',
      specimen_sez: '实验体赛兹',
      specter_tenebria: '幻影的泰妮布里雅',
      spirit_eye_celine: '灵眼的瑟琳',
      sylvan_sage_vivian: '森之贤者薇薇安',
      straze: '史瑞杰思',
      summer_break_charlotte: '暑假夏绿蒂',
      summer_disciple_alexa: '夏日学生雅莉莎',
      summertime_iseria:'南国的伊赛丽亚',
      surin: '苏琳',
      sven: '史宾',
      taeyou:'太吾',
      tamarinne: '塔玛林尔',
      taranor_guard: '塔拉诺尔禁卫队员',
      taranor_royal_guard: '塔拉诺尔王宫士兵',
      tempest_surin: '风云苏琳',
      tenebria: '泰妮布里雅',
      tieria: '黛莉亚',
      top_model_luluca: '最强模特儿璐璐卡',
      troublemaker_crozet: '不法之徒克罗泽',
      tywin: '泰温',
      verdant_adin: '新绿的艾庭',
      vigilante_leader_glenn: '自卫队队长格伦',
      vildred: '维德瑞',
      violet: '菲奥雷托',
      vivian: '薇薇安',
      wanda: '汪达',
      wanderer_silk: '流浪者席可',
      watcher_schuri: '注视者修里',
      yoonryoung: '尹凌',
      yufine: '优芬妮',
      yulha:'律荷',
      yuna: '尤娜',
      zahhak: '扎哈克',
      zealot_carmainerose: '传道者卡麦萝兹',
      zeno: '杰诺',
      zerato: '杰拉图',
      arunka: '亚露嘉',
      zio: '智武',
      savior_adin: '救援者艾庭',
      suthan: '斯坦',
      juni: '珠妮',
      lilka: '莉珈',
      talia: '达黎儿',
      talaz: '达拉士',
      peacemaker_furious: '均衡的尤贝乌斯',
      beehoo: '雨修',	
      lone_crescent_bellona: '一轮孤月维尔萝娜',	
      eligos: '艾利戈斯',	
      architect_laika:'策划者莱伊卡',
      twisted_eldolon_kayron: '扭曲亡灵凯隆',
      benimaru: '红丸',
      amid: '雅咪德',
      lua: '露雅',
      serene_purity_adin: '清玄的艾庭',
      death_dealer_ray: '死亡探究者雷伊',
      unbound_knight_arowell: '自由骑士雅洛薇',
      astromancer_Elena: '星辰的神谕艾蕾娜',
      winter:'ae-WINTER',
      giselle :'ae-GISELLE',
      ningning:'ae-NINGNING',
      karina:'ae-KARINA',   
      abigail:'阿比盖尔',   
      last_piece_karin:'最后的碎片卡琳', 
      requiem_roana:'镇魂的罗安纳', 
      ocean_breeze_luluca:'海洋香气璐璐卡', 
      lethe:'丽希', 
      navy_captain_landy:'海军上校兰蒂', 
      infinite_horizon_achates:'未知的可能性 雅卡泰丝',
      urban_shadow_choux:'都市暗影小泡芙',
      brieg:'布里克',
      veronica:'贝洛妮卡',
      midnight_gala_lilias:'夜宴莉莉亚斯',
      nahkwol:'落月',
      abyssal_Yufine:'深渊优芬妮',
      kane:'该隐',
      ezra:'艾自拉',
      amiki:'雅米琪',
      claudia:'克劳蒂亚',
      eternal_wanderer_ludwig:'永劫漂流者鲁特比',
      byblis:'维波丽斯',
      blooming_lidica:'花园丽迪卡',
      dragon_king_sharun:'龙王莎伦',
      elvira:'艾碧拉',
      leah:'蕾雅',
      laia:'莱娅',
      jenua:'济纽亚',
    },
    nicknames: {
      achates:	'小火奶',   
      adin:	'艾庭',
      adlay:	'亚迪赖',
      adventurer_ras:	'男主 转职男主 拉丝',  
      ainos:	'小暗奶',
      ains:	'艾因兹',
      aither:	'小王子',   
      alencia:	'姨妈龙 龙姨妈 小姨妈',  
      alexa:	'小水刺(未转职)',   
      all_rounder_wanda:	'转职汪达',   
      ambitious_tywin:	'光泰温 泰上皇',   
      angel_of_light_angelica:	'光水奶',   
      angelic_montmorancy:	'包子头 包包头 小水奶', 
      angelica:	'水奶 老太婆',  
      apocalypse_ravi:	'暗罗菲 暗罗',   
      aramintha:	'火响指 火法',  
      arbiter_vildred:	'暗刺 暗帝 暗25 暗弟',
      archdemon_shadow:	'魔神女主',   
      aria:	'水奶奶 大水奶 水莱莱',   
      armin:	'木敏 阿敏 木亚敏 木猫',  
      arowell:	'小光盾(未转职)',
      assassin_cartuja:	'暗熊',   
      assassin_cidd:	'暗席德 暗猴子',   
      assassin_coli:	'暗可丽',   
      auxiliary_lots:	'暗拉 暗拉兹',  
      azalea:	'亚洁理亚',
      baal_and_sezan:	'火三眼 火人偶',  
      bad_cat_armin:	'小猫咪 暗亚敏',   
      baiken:	'梅喧',
      basar:	'埃及佬 木埃及',   
      bask:	'巴思克',
      batisse:	'小暗拳',   
      belian:	'光轮椅 bla',   
      bellona:	'木扇',   
      benevolent_romann:	'光洛曼',   
      blaze_dingo:	'光厨子',   
      blood_blade_karin:	'血卡',   
      blood_moon_haste:	'暗正太',   
      briar_witch_iseria:	'暗飞剑 暗木飞 暗飞', 
      butcher_corps_inquisitor:	'哥杀 哥布林杀手',  
      camilla:	'卡米拉',
      captain_rikoris:	'先锋队长里科黎司',
      carmainerose:	'火爪',   
      carrot:	'卡罗',   
      cartuja:	'木熊',   
      cecilia:	'火龙骑',   
      celeste:	'小光弓',   
      celestial_mercedes:	'暗女主',   
      celine:	'卡琳姨妈 木阿姨 木瑟琳',   
      cerise:	'水弓',   
      cermia:	'夏娜 火夏娜',   
      challenger_dominiel:	'暗兔',   
      champion_zerato:	'暗杰 泥巴佬 泥巴哥 杰哥',
      chaos_inquisitor:	'屠杀部队员',
      chaos_sect_axe:	'暗斧',   
      charles:	'木老头 剑圣',  
      charlotte:	'火呆 女王',  
      chloe:	'水锤',   
      choux:	'小泡芙 小批芙',   
      christy:	'克莉丝媞',
      church_of_ilryos_axe:	'伊利欧斯教斧兵',
      cidd:	'木席德 木猴子',   
      clarissa:	'水修女',   
      closer_charles:	'暗老头 收银员',   
      coli:	'水可丽',   
      commander_lorina:	'暗枪',   
      commander_model_laika:	'木蜻蜓 蜻蜓队长',   
      commander_pavel:	'光狼枪 卧龙',   
      conqueror_lilias:	'llys 光莉莉',   
      corvus:	'火老头',   
      crescent_moon_rin:	'暗02 暗灵儿',  
      crimson_armin:	'光亚敏 光猫',  
      crozet:	'团长',   
      dark_corvus:	'魔神王 暗魔神 暗魔王 按摩王',  
      desert_jewel_basar:	'光埃及',   
      designer_lilibet:	'暗剪刀 llb 暗llb',   
      destina:	'木奶',   
      diene:	'圣女',   
      dingo:	'火厨子',   
      dizzy:	'DZ dizzy',  
      doll_maker_pearlhorizon:	'转职木爪',   
      dominiel:	'冰兔',   
      doris:	'朵莉思',
      eaton:	'石头人',
      eda:	'水法',
      edward_elric:	'华子',   
      elena:	'水琴',   
      elphelt_valentine:	'火兔 兔枪',  
      elson:	'光正太',   
      emilia:	'emt',
      enott:	'艾诺特',
      ervalen:	'木王子',
      fairytale_tenebria:	'水泰尼 水泰妮 水泥',  
      faithless_lidica:	'光弓',  
      falconer_kluri:	'鹰盾 鸟盾',  
      fallen_cecilia:	'暗龙 暗塞西',  
      fighter_maya:	'光玛雅',   
      flan:	'芙兰',
      free_spirit_tieria:	'小光斧',
      furious:	'开水哥',   
      general_purrgis:	'光狗 狗大将',  
      glenn:	'格伦',
      gloomyrain:	'光爪',   
      godmother:	'教母',
      great_chief_khawana:	'大族长卡瓦娜',
      guider_aither:	'光王子',   
      gunther:	'昆特大爷 坤哥',  
      haste:	'火正太',   
      hasol:	'夏率',
      hataan:	'哈坦',
      hazel:	'海兹',
      helen:	'海伦',
      helga:	'三星小木斧',   
      holiday_yufine:	'烧烤龙 喷火龙 火龙妹 包子龙 小火龙',
      holy_flame_adin:	'火艾庭',
      hurado:	'光头 三星暗法',  
      hwayoung:	'火腿',   
      ian:	'伊安',
      ilynav:	'火龙 火黑皮',
      inferno_khawazu:	'暗蕉哥 香蕉哥',   
      iseria:	'木飞剑 木飞',   
      jack_o:	'jacko',   
      januta:	'扎努塔',
      jecht:	'木狗奶',   
      jena:	'捷娜',
      judge_kise:	'光绮世 光74 光镰刀', 
      judith:	'小火刺',   
      kanna:	'农农',   
      karin:	'卡琳',
      kawerik:	'卡子 火卡子',   
      kayron:	'隆哥 凯宝 凯皇', 
      ken:	'火拳 火肯',  
      khawana:	'火妹妹',   
      khawazu:	'蕉哥',   
      kikirat_v2:	'光高达 扎古 光机器人', 
      kiris:	'毒弓',   
      kise:	'水74 新水镰 水镰刀',  
      kitty_clarissa:	'暗猫',   
      kizuna_ai:	'ai 人工智障',  
      kluri:	'鹰盾',
      krau:	'宝马哥 马哥',   
      landy:	'高达 警察 兰迪',  
      last_rider_krau:	'光宝马 光马哥 光宝马哥',
      lena:	'雷娜',   
      leo:	'木弹弓',   
      lidica:	'火弓 火高潮 高潮脸', 
      lilias:	'llys 火盾',  
      lilibet:	'剪刀 llb',  
      lionheart_cermia:	'王夏娜 狮心王 光夏娜',   
      little_queen_charlotte:	'光呆毛',   
      lorina:	'暗枪(未转职)',
      lots:	'木拉兹 木拉',  
      lucy:	'露西',
      ludwig:	'木正太',   
      luluca:	'llk',   
      luna:	'水龙',   
      magic_scholar_doris:	'小光奶 转职光奶',  
      maid_chloe:	'光锤 光女仆',  
      martial_artist_ken:	'暗拳 暗肯',  
      mascot_hazel:	'转职火奶 腹黑',  
      maya:	'火玛雅',   
      mediator_kawerik:	'暗企鹅 暗卡子',   
      melany:	'玫拉妮',
      melissa:	'吸血鬼 孕妇 棺材妹', 
      mercedes:	'火女主',   
      mercenary_helga:	'转职木斧',   
      mighty_scout:	'木老鼠',   
      milim:	'mlm 歇逼妹',   
      mirsa:	'小光刺',   
      mistychain:	'水爪',   
      montmorancy:	'小水奶(未转职)',
      moon_bunny_dominiel:	'光兔',
      mort:	'魔勒',
      mucacha:	'穆卡察',
      mui:	'缪伊',
      muse_rima:	'缪斯黎玛',
      muwi:	'武蔚',
      nemunas:	'尼姆拉斯',
      operator_sigret:	'暗眼镜 暗镰刀',  
      orte:	'奥乐缇',
      otillie:	'奥缇莉尔',
      pavel:	'木枪',   
      pearlhorizon:	'木爪',   
      peira:	'水狼',
      penelope:	'老板娘',
      pirate_captain_flan:	'暗芙兰',   
      politis:	'火双 火双子', 
      purrgis:	'木狗 反击狗',  
      pyllis:	'小暗盾(未转职)',   
      ram:	'拉姆',
      ran:	'岚',
      ras:	'男主 拉丝',   
      ravi:	'罗飞 火罗',   
      ray:	'医生 木医生',   
      rem:	'雷姆',
      remnant_violet:	'暗苹果 暗给 暗gay 大哥 暗歇逼', 
      requiemroar:	'暗爪',   
      researcher_carrot:	'卡罗 转职火法',  
      righteous_thief_roozid:	'木狗 拉条狗',  
      rikoris:	'里科黎司',
      rima:	'黎玛',
      rimuru:	'萌王',
      rin:	'木02',   
      riza_hawkeye:	'莉莎',
      roaming_warrior_leo:	'暗弹弓 暗炸弹',  
      roana:	'木瓜奶',   
      romann:	'罗曼',   
      roozid:	'鲁兹德',
      rose:	'水萝季 水罗 水罗季', 
      roy_mustang:	'大佐',   
      ruele_of_light:	'光瑞儿 光奶',  
      sage_baal_and_sezan:	'光三眼 光人偶',  
      schuri:	'火枪 火修',  
      seaside_bellona:	'SSB 水扇',  
      senya:	'赛娜',
      serila:	'火南瓜 南瓜妹',   
      sez:	'水刺',   
      shadow_knight_pyllis:	'小暗盾',
      sharun:	'毒奶',
      shadow_rose:	'暗萝季',  
      shooting_star_achates:	'SSA 暗奶 暗火奶', 
      shuna:	'朱菜',
      sigret:	'旧水镰 眼镜姐 水眼镜',  
      silk:	'木席可',   
      silver_blade_aramintha:	'光响指 光法',  
      sinful_angelica:	'暗水奶 暗奶',  
      sol:	'sol',   
      solitaria_of_the_snow:	'星法 星星法',   
      sonia:	'苏尼娅',
      specimen_sez:	'光刺 光弟弟 掏男',  
      specter_tenebria:	'暗法 暗泰妮',  
      spirit_eye_celine:	'光瑟琳',   
      sylvan_sage_vivian:	'光薇薇安 光vva',
      straze:	'史哥',   
      summer_break_charlotte:	'水呆',   
      summer_disciple_alexa:	'小水刺',
      summertime_iseria:	'火飞',
      surin:	'苏林',   
      sven:	'屎兵',   
      taeyou:	'废吾 太污',
      tamarinne:	'偶像',   
      taranor_guard:	'水桶',   
      taranor_royal_guard:	'反击水桶 反伤盾',  
      tempest_surin:	'光苏琳 光苏林',  
      tenebria:	'泰妮 火泰妮 旧火法', 
      tieria:	'三星小火斧',   
      top_model_luluca:	'暗璐璐卡 暗llk',  
      troublemaker_crozet:	'暗团',   
      tywin:	'泰温 水泰',
      verdant_adin:	'木艾庭',
      vigilante_leader_glenn:	'自卫队队长格伦',
      vildred:	'木刺 25仔 木25',  
      violet:	'木给 木gay 木苹果 木歇逼 二弟', 
      vivian:	'vva 木vva',   
      wanda:	'汪达',
      wanderer_silk:	'光席可 光黑皮',   
      watcher_schuri:	'光修里 光修理',  
      yoonryoung:	'尹凌',
      yufine:	'木龙',   
      yulha:	'绿盒 木马',
      yuna:	'学生会长',   
      zahhak:	'渣男 扎男',
      zealot_carmainerose:	'转职火爪',   
      zeno:	'丑法',
      zerato:	'水杰 冰杰 冰法', 
      arunka:	'压路机 木腿',   
      zio:	'小皇帝',   
      savior_adin:	'光艾 光艾庭 歇逼妹',   
      suthan:	'斯坦',
      juni:	'珠妮',
      lilka:	'莉珈',
      talia:	'达黎儿',
      talaz:	'达拉士',
      peacemaker_furious:	'暗开水',
      beehoo:	'雨修',
      lone_crescent_bellona:	'暗扇',
      eligos:	'boss 老大 牢大',
      architect_laika:	'光蜻蜓 Ice的本体',
      twisted_eldolon_kayron:	'光凯隆 光凯宝 亡灵凯',   
      benimaru:	'红丸',
      astromancer_Elena:	'光水琴',   
      amid: 'amd ymd 雅米德',
      lua: 'lua 路亚 卤鸭',
      death_dealer_ray: '暗雷伊 暗答辩 答辩 暗医生',
      unbound_knight_arowell: '小光盾',
      winter:'冬冬 徐冬冬',
      giselle :'吉瑟列',
      ningning:'宁宁',
      karina:'女拳 水拳 女团团长', 
      serene_purity_adin: '水艾庭',
      abigail:'阿比 吸血鬼妹妹 雅碧凯',   
      last_piece_karin:'光卡琳　千本樱', 
      requiem_roana:'暗木瓜 暗瓜', 
      ocean_breeze_luluca:'木璐璐卡 木露露卡 木llk 璐璐卡车', 
      lethe:'丽希 黑皮', 
      navy_captain_landy:'光兰蒂', 
      infinite_horizon_achates:'光火奶',
      urban_shadow_choux:'暗泡芙',
      brieg:'布里克',
      veronica:'贝洛妮卡 火弓',
      midnight_gala_lilias:'木莉莉 木ll 草莉莉 凤雏',
      nahkwol:'国风角色',
      abyssal_Yufine:'暗木龙 玉玉龙',
      kane:'该隐',
      ezra:'爱自拉',
      amiki:'雅米琪',
      claudia:'克劳蒂亚',
      eternal_wanderer_ludwig:'暗正太',
      byblis:'花园弓 大葱',
      blooming_lidica:'木高潮 花刺',
      dragon_king_sharun:'龙王莎伦',
      elvira:'艾碧拉',
      leah:'蕾雅',
      laia:'莱娅',
      jenua:'团长',
    },
    artifacts: {
      no_proc: '无神器',
      a_little_queens_crown:'小小女王的巨大王冠',
      a_symbol_of_unity:'团结的象征',
      air_to_surface_missile_misha:'空对地导弹: 美莎',
      ambrote:'安布罗泰',
      ancient_sheath:'古代剑鞘',
      black_hand_of_the_goddess: '女神的黑手',
      border_coin: '孤注一掷',
      daydream_joker: '白日梦小丑',
      dignus_orb: '尊严宝珠',
      double_edged_decrescent:'双刃下弦月',
      draco_plate: '龙族板甲',
      dux_noctis: '暗夜指挥者',
      els_fist: '艾尔之拳',
      elyha_knife: '埃里哈刀',
      exorcist_tonfa: '斗鬼的拐棍',
      hell_cutter: '地狱切割机',
      ignition_cloth_gloves: '发火布手套',
      iron_fan: '铁扇',
      jack_o_symbol: '杰克·欧的象征',
      junkyard_dog: 'Junkyard Dog',
      kaladra: '嘉拉特拉',
      last_teatime:'最后的下午茶',
      mature_sunglasses: '成熟的墨镜',
      merciless_glutton: '无情的大食客',
      otherworldly_machinery: '异界的机械',
      portrait_of_the_saviors: '救援者们的画像',
      radiant_forever: '灿烂的永恆',
      reingar_special_drink: '雷茵格尔特调饮料',
      severed_horn_wand:'被截断的犄角手杖',
      shepherd_of_the_hollow:'无为的引导者',
      sigurd_scythe: '席格勒赛斯',
      spear_of_a_new_dawn:'开辟之枪',
      spear_of_purification: '破邪之矛',
      star_of_the_deep_sea: '深海漂浮之星',
      sword_of_summer_twilight: '夏夜闪刀',
      sword_of_the_morning: '黎明剑',
      sword_of_winter_shadow: '冬晷切刀',
      tear_of_the_desert: '沙漠之泪',
      time_matter: '时间的物质',
      torn_sleeve: '撕裂的右衣袖',
      uberius_tooth: '尤贝里乌斯的臼齿',
      victorious_flag: '胜战旗帜',
      violet_talisman: '紫色护身符',
      wind_rider: '乘风者',
      wings_of_light_and_shadow:'明暗双翼',
      sword_of_adin:'循环之剑',
      no_reject:'无法拒绝的提议',
      recycle_ball:'循环念珠',
      gold_rose:'金玫瑰',
      pray:'孤独的祈祷',
      elf:'残破的祭祀长意志',
    },
    form: {
      allies_nb_buff: '我军Buff数量',
      nb_targets: '敌人数量',
      nb_hits: '攻击次数',
      target_atk_down: '目标攻击力下降',
      target_has_been_killed: '目标已被击杀',
      target_atk_up_great: '目标攻击力增加（大幅）',
      target_atk_up: '目标攻击力增加',
      target_attack: '目标攻击力',
      target_max_hp: '目标最大生命值',
      target_hp_pc: '目标当前生命值(%)',
      target_hp: '目标当前生命值',
      target_is_highest_max_hp: '目标是最高的最大生命值',
      target_speed: '目标速度',
      target_nb_buff: '目标Buff数量',
      target_nb_debuff: '目标Debuff数量',
      target_has_buff: '目标有Buff',
      target_has_debuff: '目标有Debuff',
      target_has_bleed: '目标出血',
      target_has_sleep: '目标睡眠',
      target_has_silence: '目标沉默',
      target_is_stunned: '目标眩晕',
      target_has_provoke: '目标被嘲讽',
      target_has_barrier: '目标有防护罩',
      target_magic_nailed: '目标有魔法钉',
      target_nb_bleed: '目标出血Debuff数量',
      target_bleed_detonate: '出血Debuff回合数',
      target_burn_detonate: '烧伤Debuff回合数',
      target_bomb_detonate: '目标炸弹Debuff回合数',
      caster_add: '追加攻击',
      caster_max_hp: '自身最大生命值',
      caster_hp_pc: '自身当前生命值(%)',
      caster_hp: '自身当前生命值',
      caster_hp_above_50pc: '自身当前生命值>50%',
      caster_defense: '自身防御力',
      caster_defense_up: '防御力增加',
      caster_speed: '自身速度',
      caster_speed_up: '速度提升',
      caster_debuff_speed_up: '敌方db数量',
      caster_nb_buff: '自身Buff数量',
      caster_turn: '自身回合数',
      caster_has_buff: '自身有buff',
      caster_has_debuff: '自身有Debuff',
      caster_has_flame_alchemist: '自身有焰之炼金术师BUFF',
      caster_full_fighting_spirit: '斗志最大值',
      caster_neo_phantom_sword:'自身有真幻影剑BUFF',
      caster_full_focus: '专注力最大值',
      caster_nb_focus: '专注力',
      caster_fighting_spirit: '斗志',
      caster_invincible: '自身无敌',
      caster_vigor: '自身魄力',
      caster_enrage: '自身狂气',
      caster_stealth: '自身隐身',
      caster_perception: '处于识破状态',
      caster_starshelter: '处于星之庇护状态',
      caster_multilayer_barrier: '处于多重防护状态',
      critical_hit_stack: '暴击叠加数',
      critical_hit_stack_12: '暴击叠加数',
      caster_attacked_stack_2: '烧魂次数',
      attack_skill_stack_3: '叠加数',
      attack_skill_stack_5: '攻击叠加数',
      non_attack_skill_stack_3: '非攻击叠加数',
      non_attack_skill_stack_8: '非攻击叠加数',
      non_attack_skill_stack_10: '非攻击叠加数',
      turn_stack: '回合叠加数',
      turn_stack_3: '回合叠加数',
      dead_people: '死亡人数',
      enemy_counters: '敌人反击次数',
      highest_ally_attack: '我军最高攻击力',
      ally_atk_up: '目标我军攻击力增加',
      ally_atk_up_great: '目标我军攻击力增加 (大幅)',
      skill_tree_completed: '技能树满觉醒',
      s3_stack: '3技能叠加数',
      all_allies_fire: '全体我军火属性',
      exclusive_equipment_1: '专属装备 #1',
      exclusive_equipment_2: '专属装备 #2',
      exclusive_equipment_3: '专属装备 #3',
    },
    skills: {
      non_applicable: '无',
      s1: '1技能',
      s2: '2技能',
      s3: '3技能',
      s1_soulburn: '1技能 灵魂燃烧',
      s2_soulburn: '2技能 灵魂燃烧',
      s3_soulburn: '3技能 灵魂燃烧',
      mods: '技能倍率',
      att_rate: '基础倍率(Attack Rate)',
      power: '倍率修正值(Pow!)',
      mult: '条件收益倍率',
      flat: '固定值伤害倍率',
      critBoost: '暴击增伤系数',
      pen: '防御贯穿系数',
      detonation: '激爆',
      exEq: '专属装备',
      elemAdv: '属性克制',
      afterMathFormula: '行动后',
      afterMathDmg: '行动后追加伤害',
      afterMathFormulaNoAdd: '行动后(非当前目标)',
      afterMathDmgNoAdd: '行动后追加伤害(非当前目标)',
      extraDmg: '额外伤害',
      fixed: '固定伤害',
      custom: {
        caster_target_atk_diff: '{v}% 攻击力差距',
        caster_target_spd_diff: '{v}% 速度差距',
        caster_target_def_diff: '{v}% 防御力差距',
        all_fire: '{v}% 全体我军火属性',
        allies_buff: '+{v} 我军每个Buff数量',
        caster_defense: '{v}% 自身防御力',
        caster_left_hp_pc: '{v}% 自身剩余生命值百分比',
        caster_lost_hp: '{v}% 自身失去生命值',
        caster_lost_hp_pc: '{v}% 自身失去生命值百分比',
        caster_max_hp: '{v}% 自身最大生命值',
        caster_hp_pc_over_hp_threshold: '{v}% 自身生命值百分比[高于阈值]',
        caster_rage: '{v}% 愤怒套',
        caster_speed: '{v}% 自身速度',
        caster_hp_pc_under_hp_threshold: '{v}% 自身生命值百分比[低于阈值]',
        caster_vs_target_hp_diff: '自身与目标的生命值差距: {v}%/1000hp',
        caster_multilayer_barrier: '处于多重庇护状态:{v}% ',
        dead_people: '{v}% 每个阵亡英雄',
        elemental_advantage: '{v}% 属性克制',
        per_crit_hit: '{v}% 每次暴击',
        per_target: '{v}% 每个目标',
        per_bleed: '{v}% 每个流血',
        per_fewer_target: '{v}% 每减少一个目标',
        per_focus: '{v}% 每格专注',
        per_stack: '{v}% 每叠加一次',
        per_target_debuff: '{v}% 每个Debuff',
        skill_tree: '技能树: {v}%',
        target_bleed: '目标流血: {v}%',
        target_debuff: '目标Debuff: {v}%',
        target_has_buff: '目标有Buff: {v}%',
        target_has_barrier: '目标有防护罩: {v}%',
        target_has_debuff: '目标有Debuff: {v}%',
        target_has_no_buff: '目标没有Buff: {v}%',
        target_has_silence: '目标沉默: {v}%',
        target_lost_hp_pc: '{v}% 目标失去生命值百分比',       
        target_magic_nail: '魔法钉: {v}%',
        target_max_hp: '{v}% 目标最大生命值',
        target_speed: '{v}% 目标速度',
        target_hp_pc: '目标当前生命值: {v}%',
        target_hp: '{v}%目标当前生命值',
        under_threshold: '低于阈值: {v}%',
      }
    },
    rougeP: {
achates:'未进入肉鸽池',
adin:'未进入肉鸽池',
adlay:'未进入肉鸽池',
adventurer_ras:'未进入肉鸽池',
ainos:'未进入肉鸽池',
ains:'未进入肉鸽池',
aither:'未进入肉鸽池',
alencia:'未进入肉鸽池',
alexa:'未进入肉鸽池',
all_rounder_wanda:'未进入肉鸽池',
ambitious_tywin:'未进入肉鸽池',
angel_of_light_angelica:'未进入肉鸽池',
angelic_montmorancy:'未进入肉鸽池',
angelica:'未进入肉鸽池',
apocalypse_ravi:'未进入肉鸽池',
aramintha:'未进入肉鸽池',
arbiter_vildred:'未进入肉鸽池',
archdemon_shadow:'未进入肉鸽池',
aria:'未进入肉鸽池',
armin:'未进入肉鸽池',
arowell:'未进入肉鸽池',
assassin_cartuja:'未进入肉鸽池',
assassin_cidd:'未进入肉鸽池',
assassin_coli:'未进入肉鸽池',
auxiliary_lots:'未进入肉鸽池',
azalea:'未进入肉鸽池',
baal_and_sezan:'未进入肉鸽池',
bad_cat_armin:'未进入肉鸽池',
baiken:'未进入肉鸽池',
basar:'未进入肉鸽池',
bask:'未进入肉鸽池',
batisse:'未进入肉鸽池',
belian:'未进入肉鸽池',
bellona:'未进入肉鸽池',
benevolent_romann:'未进入肉鸽池',
blaze_dingo:'未进入肉鸽池',
blood_blade_karin:'未进入肉鸽池',
blood_moon_haste:'未进入肉鸽池',
briar_witch_iseria:'未进入肉鸽池',
butcher_corps_inquisitor:'未进入肉鸽池',
camilla:'未进入肉鸽池',
captain_rikoris:'未进入肉鸽池',
carmainerose:'未进入肉鸽池',
carrot:'未进入肉鸽池',
cartuja:'未进入肉鸽池',
cecilia:'未进入肉鸽池',
celeste:'未进入肉鸽池',
celestial_mercedes:'未进入肉鸽池',
celine:'未进入肉鸽池',
cerise:'未进入肉鸽池',
cermia:'未进入肉鸽池',
challenger_dominiel:'未进入肉鸽池',
champion_zerato:'未进入肉鸽池',
chaos_inquisitor:'未进入肉鸽池',
chaos_sect_axe:'未进入肉鸽池',
charles:'未进入肉鸽池',
charlotte:'未进入肉鸽池',
chloe:'未进入肉鸽池',
choux:'未进入肉鸽池',
christy:'未进入肉鸽池',
church_of_ilryos_axe:'未进入肉鸽池',
cidd:'未进入肉鸽池',
clarissa:'未进入肉鸽池',
closer_charles:'未进入肉鸽池',
coli:'未进入肉鸽池',
commander_lorina:'未进入肉鸽池',
commander_model_laika:'未进入肉鸽池',
commander_pavel:'未进入肉鸽池',
conqueror_lilias:'未进入肉鸽池',
corvus:'未进入肉鸽池',
crescent_moon_rin:'未进入肉鸽池',
crimson_armin:'未进入肉鸽池',
crozet:'未进入肉鸽池',
dark_corvus:'未进入肉鸽池',
desert_jewel_basar:'未进入肉鸽池',
designer_lilibet:'未进入肉鸽池',
destina:'未进入肉鸽池',
diene:'未进入肉鸽池',
dingo:'未进入肉鸽池',
dizzy:'未进入肉鸽池',
doll_maker_pearlhorizon:'未进入肉鸽池',
dominiel:'未进入肉鸽池',
doris:'未进入肉鸽池',
eaton:'未进入肉鸽池',
eda:'未进入肉鸽池',
edward_elric:'未进入肉鸽池',
elena:'未进入肉鸽池',
elphelt_valentine:'未进入肉鸽池',
elson:'未进入肉鸽池',
emilia:'未进入肉鸽池',
enott:'未进入肉鸽池',
ervalen:'未进入肉鸽池',
fairytale_tenebria:'未进入肉鸽池',
faithless_lidica:'未进入肉鸽池',
falconer_kluri:'未进入肉鸽池',
fallen_cecilia:'未进入肉鸽池',
fighter_maya:'未进入肉鸽池',
flan:'未进入肉鸽池',
free_spirit_tieria:'未进入肉鸽池',
furious:'未进入肉鸽池',
general_purrgis:'未进入肉鸽池',
glenn:'未进入肉鸽池',
gloomyrain:'未进入肉鸽池',
godmother:'未进入肉鸽池',
great_chief_khawana:'未进入肉鸽池',
guider_aither:'未进入肉鸽池',
gunther:'未进入肉鸽池',
haste:'未进入肉鸽池',
hasol:'未进入肉鸽池',
hataan:'未进入肉鸽池',
hazel:'未进入肉鸽池',
helen:'未进入肉鸽池',
helga:'未进入肉鸽池',
holiday_yufine:'未进入肉鸽池',
holy_flame_adin:'未进入肉鸽池',
hurado:'未进入肉鸽池',
hwayoung:'未进入肉鸽池',
ian:'未进入肉鸽池',
ilynav:'未进入肉鸽池',
inferno_khawazu:'未进入肉鸽池',
iseria:'未进入肉鸽池',
jack_o:'未进入肉鸽池',
januta:'未进入肉鸽池',
jecht:'未进入肉鸽池',
jena:'未进入肉鸽池',
judge_kise:'未进入肉鸽池',
judith:'未进入肉鸽池',
kanna:'未进入肉鸽池',
karin:'未进入肉鸽池',
kawerik:'未进入肉鸽池',
kayron:'未进入肉鸽池',
ken:'未进入肉鸽池',
khawana:'未进入肉鸽池',
khawazu:'未进入肉鸽池',
kikirat_v2:'未进入肉鸽池',
kiris:'未进入肉鸽池',
kise:'未进入肉鸽池',
kitty_clarissa:'未进入肉鸽池',
kizuna_ai:'未进入肉鸽池',
kluri:'未进入肉鸽池',
krau:'未进入肉鸽池',
landy:'未进入肉鸽池',
last_rider_krau:'未进入肉鸽池',
lena:'未进入肉鸽池',
leo:'未进入肉鸽池',
lidica:'未进入肉鸽池',
lilias:'未进入肉鸽池',
lilibet:'未进入肉鸽池',
lionheart_cermia:'未进入肉鸽池',
little_queen_charlotte:'未进入肉鸽池',
lorina:'未进入肉鸽池',
lots:'未进入肉鸽池',
lucy:'未进入肉鸽池',
ludwig:'未进入肉鸽池',
luluca:'未进入肉鸽池',
luna:'未进入肉鸽池',
magic_scholar_doris:'未进入肉鸽池',
maid_chloe:'未进入肉鸽池',
martial_artist_ken:'未进入肉鸽池',
mascot_hazel:'未进入肉鸽池',
maya:'未进入肉鸽池',
mediator_kawerik:'未进入肉鸽池',
melany:'未进入肉鸽池',
melissa:'未进入肉鸽池',
mercedes:'未进入肉鸽池',
mercenary_helga:'未进入肉鸽池',
mighty_scout:'未进入肉鸽池',
milim:'未进入肉鸽池',
mirsa:'未进入肉鸽池',
mistychain:'未进入肉鸽池',
montmorancy:'未进入肉鸽池',
moon_bunny_dominiel:'未进入肉鸽池',
mort:'未进入肉鸽池',
mucacha:'未进入肉鸽池',
mui:'未进入肉鸽池',
muse_rima:'未进入肉鸽池',
muwi:'未进入肉鸽池',
nemunas:'未进入肉鸽池',
operator_sigret:'未进入肉鸽池',
orte:'未进入肉鸽池',
otillie:'未进入肉鸽池',
pavel:'未进入肉鸽池',
pearlhorizon:'未进入肉鸽池',
peira:'未进入肉鸽池',
penelope:'未进入肉鸽池',
pirate_captain_flan:'未进入肉鸽池',
politis:'未进入肉鸽池',
purrgis:'未进入肉鸽池',
pyllis:'未进入肉鸽池',
ram:'未进入肉鸽池',
ran:'未进入肉鸽池',
ras:'未进入肉鸽池',
ravi:'未进入肉鸽池',
ray:'未进入肉鸽池',
rem:'未进入肉鸽池',
remnant_violet:'未进入肉鸽池',
requiemroar:'未进入肉鸽池',
researcher_carrot:'未进入肉鸽池',
righteous_thief_roozid:'未进入肉鸽池',
rikoris:'未进入肉鸽池',
rima:'未进入肉鸽池',
rimuru:'未进入肉鸽池',
rin:'未进入肉鸽池',
riza_hawkeye:'未进入肉鸽池',
roaming_warrior_leo:'未进入肉鸽池',
roana:'未进入肉鸽池',
romann:'未进入肉鸽池',
roozid:'未进入肉鸽池',
rose:'未进入肉鸽池',
roy_mustang:'未进入肉鸽池',
ruele_of_light:'未进入肉鸽池',
sage_baal_and_sezan:'未进入肉鸽池',
schuri:'未进入肉鸽池',
seaside_bellona:'未进入肉鸽池',
senya:'未进入肉鸽池',
serila:'未进入肉鸽池',
sez:'未进入肉鸽池',
shadow_knight_pyllis:'未进入肉鸽池',
sharun:'未进入肉鸽池',
shadow_rose:'未进入肉鸽池',
shooting_star_achates:'未进入肉鸽池',
shuna:'未进入肉鸽池',
sigret:'未进入肉鸽池',
silk:'未进入肉鸽池',
silver_blade_aramintha:'未进入肉鸽池',
sinful_angelica:'未进入肉鸽池',
sol:'未进入肉鸽池',
solitaria_of_the_snow:'未进入肉鸽池',
sonia:'未进入肉鸽池',
specimen_sez:'未进入肉鸽池',
specter_tenebria:'未进入肉鸽池',
spirit_eye_celine:'未进入肉鸽池',
sylvan_sage_vivian:'未进入肉鸽池',
straze:' (v1.0)速度套 什么神器 4000 300 350',
summer_break_charlotte:'未进入肉鸽池',
summer_disciple_alexa:'未进入肉鸽池',
summertime_iseria:'未进入肉鸽池',
surin:'未进入肉鸽池',
sven:'未进入肉鸽池',
taeyou:'未进入肉鸽池',
tamarinne:'未进入肉鸽池',
taranor_guard:'未进入肉鸽池',
taranor_royal_guard:'未进入肉鸽池',
tempest_surin:'未进入肉鸽池',
tenebria:'未进入肉鸽池',
tieria:'未进入肉鸽池',
top_model_luluca:'未进入肉鸽池',
troublemaker_crozet:'未进入肉鸽池',
tywin:'未进入肉鸽池',
verdant_adin:'未进入肉鸽池',
vigilante_leader_glenn:'未进入肉鸽池',
vildred:'未进入肉鸽池',
violet:'未进入肉鸽池',
vivian:'未进入肉鸽池',
wanda:'未进入肉鸽池',
wanderer_silk:'未进入肉鸽池',
watcher_schuri:'未进入肉鸽池',
yoonryoung:'未进入肉鸽池',
yufine:'未进入肉鸽池',
yulha:'未进入肉鸽池',
yuna:'未进入肉鸽池',
zahhak:'未进入肉鸽池',
zealot_carmainerose:'未进入肉鸽池',
zeno:'未进入肉鸽池',
zerato:'未进入肉鸽池',
arunka:'未进入肉鸽池',
zio:'未进入肉鸽池',
savior_adin:'未进入肉鸽池',
suthan:'未进入肉鸽池',
juni:'未进入肉鸽池',
lilka:'未进入肉鸽池',
talia:'未进入肉鸽池',
talaz:'未进入肉鸽池',
peacemaker_furious:'未进入肉鸽池',
beehoo:'未进入肉鸽池',
lone_crescent_bellona:'未进入肉鸽池',
eligos:'未进入肉鸽池',
architect_laika:'未进入肉鸽池',
twisted_eldolon_kayron:'未进入肉鸽池',
benimaru:'未进入肉鸽池',
amid:'未进入肉鸽池',
lua:'未进入肉鸽池',
serene_purity_adin:'未进入肉鸽池',
death_dealer_ray:'未进入肉鸽池',
unbound_knight_arowell:'未进入肉鸽池',
astromancer_Elena:'未进入肉鸽池',
winter:'未进入肉鸽池',
giselle :'未进入肉鸽池',
ningning:'未进入肉鸽池',
karina:'未进入肉鸽池',
abigail:'未进入肉鸽池',
last_piece_karin:'未进入肉鸽池',
requiem_roana:'未进入肉鸽池'

      },
    
    info: {
      }
  }
};

const heroName = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return heroes[id].name;
  } else {
    return i18n[lang].heroes[id] || heroes[id].name;
  }
};

const heroNicknames = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  return i18n[lang].nicknames[id] || '';
};

const nickNamesShow = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  return i18n[lang].nicknames[id] || '';
};
const rouge = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  return i18n[lang].rougeP[id] || '';
};


const artifactName = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return artifacts[id] ? artifacts[id].name : 'No Artifact Proc';
  } else {
    return i18n[lang].artifacts[id || 'no_proc'] || artifacts[id].name;
  }
};

const formLabel = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return elements[id].label;
  } else {
    return i18n[lang].form[id] || elements[id].label;
  }
};

const skillLabel = (id, soulburn = false) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return (id === 'non_applicable') ? 'n/a' : i18n[lang].skills[id] || id.toUpperCase() + (soulburn ? ' Soulburn' : '');
  } else {
    id = soulburn ? id+'_soulburn' : id;
    return i18n[lang].skills[id] || i18n['en'].skills[id] || id.toUpperCase();
  }
};

const compareSkillLabel = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  const idSplit = id.split('_');
  id = idSplit[0];
  const extra = idSplit[1] || '';

  let display;
  if (lang === 'en') {
    display = id.toUpperCase();
  } else {
    display = i18n[lang].skills[id] || id.toUpperCase();
  }

  if (extra === 'sb') {
    display += '<i class="fas fa-fire"></i>';
  } else if (extra!== '') {
    display += '<i class="far fa-plus-square"></i>';
  }

  return display
};

const getSkillModTip = (tips) => {
  if (!tips) return '';

  const output = [];
  for (const key of Object.keys(tips)) {
    let lang = document.getElementById('root').getAttribute('lang');
    if (i18n[lang].skills['custom'] === undefined) lang = 'en';
    if (i18n[lang].skills['custom'][key] === undefined) lang = 'en';

    if (i18n[lang].skills['custom'][key] === undefined) return null;
    output.push((i18n[lang].skills['custom'][key]).replace('{v}', tips[key]));
  }

  return `(${output.join(', ')})`
}

const infoLabel = (key) => {
  let lang = document.getElementById('root').getAttribute('lang');
  if (i18n[lang].info === undefined) lang = 'en';

  return i18n[lang].info[key] || i18n['en'].info[key] || '';
}
