const i18n = {
  en: {
    nicknames: {
      ambitious_tywin: 'aywin ml.tywin mltywin',
      angelic_montmorancy: 'momo',
      arbiter_vildred: 'arby',
      assassin_cartuja: 'fatcat',
      assassin_cidd: 'a.cidd accid',
      assassin_coli: 'a.coli acoli',
      auxiliary_lots: 'a.lots alots',
      benevolent_romann: 'broman',
      blood_blade_karin: 'bbk',
      challenger_dominiel: 'c.dom cdom',
      champion_zerato: 'c.zerato czerato',
      church_of_ilryos_axe: 'axe god axegod',
      crescent_moon_rin: 'ml.rin mlrin',
      crimson_armin: 'c.armin carmin',
      dark_corvus: 'dc DC',
      desert_jewel_basar: 'dj.basar djbasar',
      faithless_lidica: 'f.lidica flidica',
      falconer_kluri: 'f.kluri fkluri',
      fallen_cecilia: 'f.cc fcc',
      fighter_maya: 'f.maya fmaya',
      general_purrgis: 'g.purrgis gpurrgis',
      holiday_yufine: 'hufine',
      jack_o: 'jacko',
      judge_kise: 'j.kise jkise',
      maid_chloe: 'ml.chloe mlchloe',
      martial_artist_ken: 'ml.ken mlken',
      mort: 'mortelix',
      sage_baal_and_sezan: 'ml.baal mlbaal',
      shooting_star_achates: 'ssa',
      seaside_bellona: 'ssb',
      silver_blade_aramintha: 'ml.aramintha mlaramintha',
      sinful_angelica: 'ml.angelica mlangelica',
      specimen_sez: 'ml.sez mlsez',
      specter_tenebria: 'specte ml.tenebria mltenebria',
      taranor_guard: 'tg',
      troublemaker_crozet: 'ml.crozet mlcrozet',
      wanderer_silk: 'ml.silk mlsilk',
    },
    skills: {
      mods: 'Skill Modifiers',
      att_rate: 'Attack Rate',
      power: 'Power',
      mult: 'Mult Mod',
      flat: 'Flat Mod',
      critBoost: 'Crit Dmg',
      pen: 'Penetrate',
      detonation: 'Detonation',
      exEq: 'Excl. Equipment',
      elemAdv: 'Elemental Adv',
      afterMathFormula: 'Aftermath',
      afterMathDmg: 'Aftermath Dmg',
      extraDmg: 'Extra Dmg',
      fixed: 'Fixed Dmg',
      custom: {
        caster_target_atk_diff: '{v}% Attack Difference',
        caster_target_spd_diff: '{v}% Speed Difference',
        caster_target_def_diff: '{v}% Def Difference',
        all_fire: '{v}% Team Fire',
        allies_buff: '+{v} per Buff',
        caster_defense: '{v}% Defense',
        caster_left_hp_pc: '{v}% remaining HP%',
        caster_lost_hp: '{v}% lost HP',
        caster_lost_hp_pc: '{v}% lost HP%',
        caster_max_hp: '{v}% max HP',
        caster_hp_pc_over_hp_threshold: '{v}% HP% [above threshold]',
        caster_rage: '{v}% Rage',
        caster_speed: '{v}% Speed',
        caster_hp_pc_under_hp_threshold: '{v}% HP% [below threshold]',
        caster_vs_target_hp_diff: 'Caster vs Target HP Diff: {v}%/1000hp',
        dead_people: '{v}% per dead hero',
        elemental_advantage: '{v}% Elem. Adv.',
        per_crit_hit: '{v}% per Critical Hit',
        per_target: '{v}% per Target',
        per_bleed: '{v}% per Bleed',
        per_fewer_target: '{v}% per fewer Target',
        per_focus: '{v}% per Focus',
        per_stack: '{v}% per Stack',
        per_target_debuff: '{v}% per Debuff',
        skill_tree: 'Skill Tree: {v}%',
        target_bleed: 'Target Bleed: {v}%',
        target_debuff: 'Target Debuff: {v}%',
        target_has_buff: 'Target has Buff: {v}%',
        target_has_debuff: 'Target has Debuff: {v}%',
        target_has_barrier: 'Target has Barrier: {v}%',
        target_has_no_buff: 'Target has no Buff: {v}%',
        target_lost_hp_pc: '{v}% Target lost HP%',
        target_magic_nail: 'Magic Nail: {v}%',
        target_max_hp: '{v}% Target max HP',
        target_speed: '{v}% Target Speed',
        under_threshold: 'Below Threshold: {v}%',
      }
    },
    info: {
      alencia_trample: 'Trample',
      aria_scaling: 'Heads up: Crit Damage scaling out of lost HP% is probably wrong. Skill multipliers are accurate.',
      balance_op_sigret: 'Balance Update: Added Speed scaling, lowered Attack scaling: S2: 0.8 -> 0.75 / S3 1.1 -> 1',
      lqc_s3_splash: 'S3 Splash',
      ml_celine_nimble_sword: 'Nimble Sword',
      s1_extra_attack: 'S1 Extra Attack',
      s1_soulburn: 'S1 Soulburn',
      s2_wave_2: 'S2 Wave 2',
      s2_counter: 'S2 (Counter)',
      s2_wave_3: 'S2 Wave 3',
      sez_explosion: 'Explosion',
      victorious_flag: 'Elemental advantage must be enabled to see benefits from this artifact; doesn\'t apply to light and dark heroes',
      yoonryoung_slash: 'Dazzling Slash'
    }
  },
  zhCN: {
    heroes: {
      achates: '雅卡泰丝',
      adin: '艾庭',
      adlay: '亚迪赖',
      adventurer_ras: '冒险家拉斯',
      ainos: '艾诺斯',
      ains: '艾因兹',
      aither: '埃德勒',
      alencia: '艾莲西雅',
      alexa: '雅莉莎',
      all_rounder_wanda: '疑难杂症专家汪达',
      ambitious_tywin: '野心份子泰温',
      angel_of_light_angelica: '光之天使安洁莉卡',
      angelic_montmorancy: '守护天使蒙茉朗西',
      angelica: '安洁莉卡',
      apocalypse_ravi: '末日萝菲',
      aramintha: '雅拉敏塔',
      arbiter_vildred: '执行官维德瑞',
      archdemon_shadow: '魔神的暗影',
      aria: '艾莉雅',
      armin: '亚敏',
      arowell: '雅洛薇',
      assassin_cartuja: '杀手卡尔图哈',
      assassin_cidd: '杀手席德',
      assassin_coli: '杀手可丽',
      auxiliary_lots: '辅助型拉兹',
      azalea: '亚洁理亚',
      baal_and_sezan: '巴尔&塞尚',
      bat_cat_armin: '坏坏猫亚敏',
      baiken: '梅喧',
      basar: '巴萨尔',
      bask: '巴思克',
      batisse: '巴托斯',
      belian: '伯里安',
      bellona: '维尔萝娜',
      benevolent_romann: '仁慈的洛曼',
      blaze_dingo: '烈火汀果',
      blood_blade_karin: '血剑卡琳',
      blood_moon_haste: '赤月的贵族海斯特',
      briar_witch_iseria: '灰光森林的伊赛丽亚',
      butcher_corps_inquisitor: '混沌教屠杀追击者',
      camilla: '卡米拉',
      captain_rikoris: '先锋队长里科黎司',
      carmainerose: '卡麦萝兹',
      carrot: '卡萝',
      cartuja: '卡尔图哈',
      cecilia: '赛西莉亚',
      celeste: '赛雷斯特',
      celestial_mercedes: '外太空的玫勒赛德丝',
      celine: '瑟琳',
      cerise: '赛瑞丝',
      cermia: '洁若米亚',
      challenger_dominiel: '挑战者多米妮尔',
      champion_zerato: '终结者杰拉图',
      chaos_inquisitor: '屠杀部队员',
      chaos_sect_axe: '混沌教巨斧大将军',
      charles: '查尔斯',
      charlotte: '夏绿蒂',
      chloe: '克萝爱',
      choux: '小泡芙',
      christy: '克莉丝媞',
      church_of_ilryos_axe: '伊利欧斯教斧兵',
      cidd: '席德',
      clarissa: '克莱莉莎',
      closer_charles: '末日指挥官查尔斯',
      coli: '可丽',
      commander_lorina: '指挥官萝里娜',
      commander_model_laika: '指挥型莱伊卡',
      commander_pavel: '司令官帕贝尔',
      conqueror_lilias: '支配者莉莉亚斯',
      corvus: '科尔布思',
      crescent_moon_rin: '新月舞姬铃儿',
      crimson_armin: '红焰亚敏',
      crozet: '克罗泽',
      dark_corvus: '黑暗的科尔布思',
      desert_jewel_basar: '沙漠宝石巴萨尔',
      designer_lilibet: '设计师莉莉贝',
      destina: '戴丝蒂娜',
      diene: '迪埃妮',
      dingo: '汀果',
      dizzy: '蒂姬',
      doll_maker_pearlhorizon: '制偶师波萝莱珍',
      dominiel: '多米妮尔',
      doris: '朵莉思',
      eaton: '伊顿',
      eda:'艾妲',
      edward_elric: '爱德华·爱力克',
      elena: '艾蕾娜',
      elphelt_valentine: '爱尔菲特',
      elson: '艾尔森',
      emilia:'爱蜜莉雅',
      enott: '艾诺特',
      ervalen: '艾尔巴伦',
      fairytale_tenebria: '童话泰妮布里雅',
      faithless_lidica: '无神论者丽迪卡',
      falconer_kluri: '鹰猎人可露莉',
      fallen_cecilia: '堕落的赛西莉亚',
      fighter_maya: '战斗型玛雅',
      flan: '芙兰',
      free_spirit_tieria: '永恆不变的黛莉亚',
      furious: '尤贝乌斯',
      general_purrgis: '大将法济斯',
      glenn: '格伦',
      gloomyrain: '格鲁美兰',
      godmother: '教母',
      great_chief_khawana: '大族长卡瓦娜',     
      guider_aither: '求道者埃德勒',
      gunther: '坤特',
      haste: '海斯特',
      hasol: '夏率',
      hataan: '哈坦',
      hazel: '海兹',
      helen: '海伦',
      helga: '赫尔嘉',
      holiday_yufine: '度假风优芬妮',
      holy_flame_adin: '圣炎的艾庭',
      hurado: '修拉杜',
      hwayoung: '和英',
      ian: '伊安',
      ilynav: '伊莉娜芙',
      inferno_khawazu: '烈焰的卡瓦朱',
      iseria: '伊赛丽亚',
      jack_o: '杰克·欧',
      januta: '扎努塔',
      jecht: '杰克托',
      jena: '捷娜',
      judge_kise: '审判者绮世',
      judith: '茱迪丝',
      kanna: '暴击型卡农',
      karin: '卡琳',
      kawerik: '卡威利',
      kayron: '凯隆',
      ken: '肯恩',
      khawana: '卡瓦娜',
      khawazu: '卡瓦朱',
      kikirat_v2: '奇奇拉特V.2',
      kiris: '奇丽丝',
      kise: '绮世',
      kitty_clarissa: '猫咪克莱莉莎',
      kizuna_ai: '绊爱',
      kluri: '可露莉',
      krau: '克劳乌',
      landy: '兰蒂',
      last_rider_krau:'最后的骑士克劳乌',
      lena: '雷娜',
      leo: '雷欧',
      lidica: '丽迪卡',
      lilias: '莉莉亚斯',
      lilibet: '莉莉贝',
      lionheart_cermia: '狮心王洁若米亚',
      little_queen_charlotte: '年轻的女王夏绿蒂',
      lorina: '萝里娜',
      lots: '拉兹',
      lucy: '露西',
      ludwig: '鲁特比',
      luluca: '璐璐卡',
      luna: '露娜',
      magic_scholar_doris: '魔法学者朵莉思',
      maid_chloe: '仆人克萝爱',
      martial_artist_ken: '武斗家肯恩',
      mascot_hazel: '吉祥物海兹',
      maya: '玛雅',
      mediator_kawerik: '协调者卡威利',
      melany: '玫拉妮',
      melissa: '梅丽莎',
      mercedes: '玫勒赛德丝',
      mercenary_helga: '自由自在的佣兵赫尔嘉',
      mighty_scout: '侦察兵玛伊堤',
      milim: '米莉姆',
      mirsa: '米勒莎',
      mistychain: '美丝缇彩',
      montmorancy: '蒙茉朗西',
      moon_bunny_dominiel: '月兔多米妮尔',
      mort:'魔勒',
      mucacha: '穆卡察',
      mui:'缪伊',
      muse_rima: '缪斯黎玛',
      muwi: '武蔚',
      nemunas: '尼姆拉斯',
      operator_sigret: '操作员赛珂兰特',
      orte: '奥乐缇',
      otillie: '奥缇莉尔',
      pavel: '帕贝尔',
      pearlhorizon: '波萝莱珍',
      peira: '沛伊拉',
      penelope: '潘尼罗佩',
      pirate_captain_flan: '海盗船长芙兰',
      politis: '佛里蒂丝',
      purrgis: '法济斯',
      pyllis: '费莉丝',
      ram:'拉姆',
      ran: '岚',
      ras: '拉斯',
      ravi: '萝菲',
      ray: '雷伊',
      rem:'雷姆',
      remnant_violet: '残影的菲奥雷托',
      requiemroar: '雷奎姆洛',
      researcher_carrot: '研究者卡萝',
      righteous_thief_roozid: '义贼鲁兹德',
      rikoris: '里科黎司',
      rima: '黎玛',
      rimuru: '利姆路',
      rin: '铃儿',
      riza_hawkeye: '莉莎·霍克爱',
      roaming_warrior_leo: '流浪勇士雷欧',
      roana: '罗安纳',
      romann: '洛曼',
      roozid: '鲁兹德',
      rose: '萝季',
      roy_mustang: '罗伊·马斯坦古',
      ruele_of_light: '光之瑞儿',
      sage_baal_and_sezan: '贤者巴尔&塞尚',
      schuri: '修里',
      seaside_bellona: '海边的维尔萝娜',
      senya:'赛娜',
      serila: '塞丽拉',
      sez: '赛兹',
      shadow_knight_pyllis: '黑骑士费莉丝',
      sharun: '莎伦',
      shadow_rose: '暗影萝季',
      shooting_star_achates: '流星雅卡泰丝',
      shuna: '朱菜',
      sigret: '赛珂兰特',
      silk: '席可',
      silver_blade_aramintha: '白银刀刃的雅拉敏塔',
      sinful_angelica: '罪戾的安洁莉卡',
      sol: '索尔',
      solitaria_of_the_snow: '雪国的苏莉塔妮亚',
      sonia: '苏尼娅',
      specimen_sez: '实验体赛兹',
      specter_tenebria: '幻影的泰妮布里雅',
      spirit_eye_celine: '灵眼的瑟琳',
      straze: '史瑞杰思',
      summer_break_charlotte: '暑假夏绿蒂',
      summer_disciple_alexa: '夏日学生雅莉莎',
      summertime_iseria:'南国的伊赛丽亚',
      surin: '苏琳',
      sven: '史宾',
      taeyou:'太吾',
      tamarinne: '塔玛林尔',
      taranor_guard: '塔拉诺尔禁卫队员',
      taranor_royal_guard: '塔拉诺尔王宫士兵',
      tempest_surin: '风云苏琳',
      tenebria: '泰妮布里雅',
      tieria: '黛莉亚',
      top_model_luluca: '最强模特儿璐璐卡',
      troublemaker_crozet: '不法之徒克罗泽',
      tywin: '泰温',
      verdant_adin: '新绿的艾庭',
      vigilante_leader_glenn: '自卫队队长格伦',
      vildred: '维德瑞',
      violet: '菲奥雷托',
      vivian: '薇薇安',
      wanda: '汪达',
      wanderer_silk: '流浪者席可',
      watcher_schuri: '注视者修里',
      yoonryoung: '尹凌',
      yufine: '优芬妮',
      yulha:'律荷',
      yuna: '尤娜',
      zahhak: '扎哈克',
      zealot_carmainerose: '传道者卡麦萝兹',
      zeno: '杰诺',
      zerato: '杰拉图',
      arunka: '亚露嘉',
      zio: '智武',
      savior_adin: '光艾庭',
      suthan: '斯坦',
      juni: '珠妮',
      lilka: '莉珈',
      talia: '达黎儿',
      talaz: '达拉士',
      peacemaker_furious: '均衡的尤贝乌斯',
      beehoo: '雨修',	
      astromancer_Elena: '星辰的神谕艾蕾娜',
    },
    nicknames: {
      achates: '火奶',
      aither: '小王子',
      alencia: '姨妈龙 龙姨妈',
      alexa: '小水刺',
      all_rounder_wanda: '转职汪达',
      ambitious_tywin: '光泰温',
      angelic_montmorancy: '包子头 包包头 小水奶',
      angelica: '大水奶 老太婆',
      apocalypse_ravi: '暗罗菲',
      aramintha: '火响指 火法',
      arbiter_vildred: '暗刺 暗帝 暗25 暗弟',
      archdemon_shadow: '魔神女主',
      armin: '木敏 阿敏',
      assassin_cartuja: '暗熊',
      assassin_cidd: '暗席德',
      assassin_coli: '暗可丽',
      auxiliary_lots: '暗拉 暗拉兹',
      adventurer_ras: '男主 转职男主',
      baal_and_sezan: '火三眼 火人偶',
      basar: '埃及佬',
      batisse: '小暗拳',
      belian: '光轮椅',
      bellona: '木扇',
      benevolent_romann: '光洛曼',
      blaze_dingo: '光厨子',
      blood_blade_karin: '血卡',
      blood_moon_haste: '暗正太',
      briar_witch_iseria: '暗飞剑 暗木飞 暗弓',
      butcher_corps_inquisitor: '哥杀 哥布林杀手',
      carmainerose: '火爪',
      carrot: '卡罗',
      cartuja: '木熊',
      cecilia: '火龙骑',
      celeste: '三星光弓',
      celestial_mercedes: '暗女主',
      celine: '卡琳姨妈',
      cerise: '水弓',
      cermia: '夏娜',
      challenger_dominiel: '暗兔',
      champion_zerato: '暗杰 泥巴佬 泥巴哥 杰哥',
      chaos_sect_axe: '暗斧',
      charles: '木老头 剑圣',
      charlotte: '火呆毛 女王',
      choux: '苏',
      chloe: '水锤',
      cidd: '木席德',
      clarissa: '水修女',
      coli: '水可丽',
      commander_lorina: '暗枪',
      corvus: '火老头',
      crescent_moon_rin: '暗02 暗灵儿',
      crimson_armin: '光亚敏 光猫',
      crozet: '团长',
      dark_corvus: '魔神王 暗魔神',
      desert_jewel_basar: '光埃及',
      designer_lilibet: '暗剪刀',
      destina: '木奶',
      diene: '圣女',
      dingo: '火厨子',
      dizzy: 'DZ dizzy',
      doll_maker_pearlhorizon: '转职木爪',
      dominiel: '冰兔',
      elena: '水琴',
      elphelt_valentine: '火兔 兔枪',
      elson: '光正太',
      fairytale_tenebria: '水泰尼 水泰妮',
      faithless_lidica: '光弓 光高潮',
      falconer_kluri: '鹰盾 鸟盾',
      fallen_cecilia: '暗龙 暗塞西',
      fighter_maya: '光玛雅',
      furious: '开水哥',
      general_purrgis: '光狗 狗大将',
      gloomyrain: '光爪',
      guider_aither: '光王子',
      gunther: '昆特大爷 坤哥',
      haste: '火正太',
      helga: '三星小木斧',
      holiday_yufine: '烧烤龙 喷火龙 火龙妹 包子龙',
      hurado: '光头 三星暗法',
      inferno_khawazu: '暗蕉哥',
      iseria: '木飞剑',
      jecht: '木狗奶',
      judge_kise: '光绮世 光74 光镰刀',
      judith: '小火刺',
      kawerik: '威哥',
      kayron: '隆哥 凯宝 凯皇',
      kizuna_ai: 'ai vtb',
      ken: '火拳 火肯',
      khawana: '火妹妹',
      khawazu: '蕉哥',
      kikirat_v2: '光高达 扎古 光机器人',
      kiris: '毒弓',
      kise: '水74 新水镰',
      kitty_clarissa: '暗猫',
      krau: '宝马哥',
      landy: '高达 警察',
      last_rider_krau:'光宝马 宝马00 骑摩托',
      lena: '水拳',
      leo: '木弹弓',
      lidica: '火弓 火高潮 高潮脸',
      lilias: 'llys 火盾',
      lilibet: '剪刀 llb',
      little_queen_charlotte: '光呆毛',
      lots: '木拉兹 木拉',
      ludwig: '木正太',
      luluca: 'llk',
      luna: '水龙',
      magic_scholar_doris: '小光奶 转职光奶',
      maid_chloe: '光锤 光女仆',
      martial_artist_ken: '暗拳 暗肯',
      mascot_hazel: '转职火奶 腹黑',
      maya: '火玛雅',
      mediator_kawerik: '暗企鹅',
      melissa: '吸血鬼 孕妇 棺材妹',
      mercedes: '女主',
      mercenary_helga: '转职木斧',
      mighty_scout: '木老鼠',
      mirsa: '三星小光刺',
      mistychain: '水爪',
      mui:'木鞭子 驯兽师 马戏团',
      operator_sigret: '暗眼镜 暗镰刀',
      pavel: '木枪',
      pearlhorizon: '木爪',
      politis: '机械城主 火法 轮椅妹',
      purrgis: '木狗 反击狗',
      pyllis: '三星暗盾',
      ray: '男医生',
      ras: '男主',
      ravi: '罗飞',
      remnant_violet: '暗苹果 暗给 暗gay',
      requiemroar: '暗爪',
      researcher_carrot: '卡罗 转职火法',
      righteous_thief_roozid: '木狗 拉条狗',
      rin: '木02',
      roaming_warrior_leo: '暗弹弓 暗炸弹',
      roana: '木瓜奶',
      romann: '罗曼',
      rose: '水萝季 水罗 水罗季',
      ruele_of_light: '瑞儿 光奶',
      sage_baal_and_sezan: '光三眼 光人偶',
      schuri: '火枪 火修',
      shooting_star_achates: 'SSA 暗奶 暗火奶',
      seaside_bellona: 'SSB 水扇',
      serila: '火南瓜',
      sez: '水刺',
      shadow_rose: '暗萝季 暗罗季',
      sigret: '旧水镰 眼镜姐',
      silk: '木席可',
      silver_blade_aramintha: '光响指 光法',
      sinful_angelica: '暗水奶 暗奶',
      sol: 'sol',
      specimen_sez: '光刺 光弟弟',
      specter_tenebria: '暗法 暗泰妮',
      surin: '苏林',
      sven: '屎兵',
      tamarinne: '偶像',
      taranor_guard: '水桶',
      taranor_royal_guard: '反击水桶 反伤盾',
      tempest_surin: '光苏琳 光苏林',
      tenebria: '泰妮 火泰妮 旧火法',
      tieria: '三星小火斧',
      top_model_luluca: '暗璐璐卡 llk',
      troublemaker_crozet: '暗团长',
      vildred: '木刺 25仔',
      violet: '木给 木gay 木苹果',
      vivian: 'vva',
      wanderer_silk: '光席可',
      watcher_schuri: '光修里 光修理',
      yufine: '木龙',
      yuna: '学生会长',
      zealot_carmainerose: '转职火爪',
      zerato: '水杰 冰杰 冰法',
    },
    artifacts: {
      no_proc: '无神器',
      a_little_queens_crown:'小小女王的巨大王冠',
      a_symbol_of_unity:'团结的象征',
      air_to_surface_missile_misha:'空对地导弹: 美莎',
      ambrote:'安布罗泰',
      ancient_sheath:'古代剑鞘',
      black_hand_of_the_goddess: '女神的黑手',
      border_coin: '孤注一掷',
      daydream_joker: '白日梦小丑',
      dignus_orb: '尊严宝珠',
      double_edged_decrescent:'双刃下弦月',
      draco_plate: '龙族板甲',
      dux_noctis: '暗夜指挥者',
      els_fist: '艾尔之拳',
      elyha_knife: '埃里哈刀',
      exorcist_tonfa: '斗鬼的拐棍',
      hell_cutter: '地狱切割机',
      ignition_cloth_gloves: '发火布手套',
      iron_fan: '铁扇',
      jack_o_symbol: '杰克·欧的象征',
      junkyard_dog: 'Junkyard Dog',
      kaladra: '嘉拉特拉',
      last_teatime:'最后的下午茶',
      mature_sunglasses: '成熟的墨镜',
      merciless_glutton: '无情的大食客',
      otherworldly_machinery: '异界的机械',
      portrait_of_the_saviors: '救援者们的画像',
      radiant_forever: '灿烂的永恆',
      reingar_special_drink: '雷茵格尔特调饮料',
      severed_horn_wand:'被截断的犄角手杖',
      shepherd_of_the_hollow:'无为的引导者',
      sigurd_scythe: '席格勒赛斯',
      spear_of_a_new_dawn:'开辟之枪',
      spear_of_purification: '破邪之矛',
      star_of_the_deep_sea: '深海漂浮之星',
      sword_of_summer_twilight: '夏夜闪刀',
      sword_of_the_morning: '黎明剑',
      sword_of_winter_shadow: '冬晷切刀',
      tear_of_the_desert: '沙漠之泪',
      time_matter: '时间的物质',
      torn_sleeve: '撕裂的右衣袖',
      uberius_tooth: '尤贝里乌斯的臼齿',
      victorious_flag: '胜战旗帜',
      violet_talisman: '紫色护身符',
      wind_rider: '乘风者',
      wings_of_light_and_shadow:'明暗双翼',
      sword_of_adin:'循环之剑',
    },
    form: {
      allies_nb_buff: '我军Buff数量',
      nb_targets: '敌人数量',
      nb_hits: '攻击次数',
      target_atk_down: '目标攻击力下降',
      target_has_been_killed: '目标已被击杀',
      target_atk_up_great: '目标攻击力增加（大幅）',
      target_atk_up: '目标攻击力增加',
      target_attack: '目标攻击力',
      target_max_hp: '目标最大生命值',
      target_hp_pc: '目标当前生命值(%)',
      target_hp: '目标当前生命值',
      target_is_highest_max_hp: '目标是最高的最大生命值',
      target_speed: '目标速度',
      target_nb_buff: '目标Buff数量',
      target_nb_debuff: '目标Debuff数量',
      target_has_buff: '目标有Buff',
      target_has_debuff: '目标有Debuff',
      target_has_bleed: '目标出血',
      target_has_sleep: '目标睡眠',
      target_has_silence: '目标沉默',
      target_is_stunned: '目标眩晕',
      target_has_provoke: '目标被嘲讽',
      target_has_barrier: '目标有防护罩',
      target_magic_nailed: '目标有魔法钉',
      target_nb_bleed: '目标出血Debuff数量',
      target_bleed_detonate: '出血Debuff回合数',
      target_burn_detonate: '烧伤Debuff回合数',
      target_bomb_detonate: '目标炸弹Debuff回合数',
      caster_max_hp: '自身最大生命值',
      caster_hp_pc: '自身当前生命值(%)',
      caster_hp: '自身当前生命值',
      caster_hp_above_50pc: '自身当前生命值>50%',
      caster_defense: '自身防御力',
      caster_defense_up: '防御力增加',
      caster_speed: '自身速度',
      caster_speed_up: '速度提升',
      caster_nb_buff: '自身Buff数量',
      caster_turn: '自身回合数',
      caster_has_debuff: '自身有Debuff',
      caster_has_flame_alchemist: '自身有焰之炼金术师BUFF',
      caster_full_fighting_spirit: '斗志最大值',
      caster_full_focus: '专注力最大值',
      caster_nb_focus: '专注力',
      caster_fighting_spirit: '斗志',
      caster_invincible: '自身无敌',
      caster_vigor: '自身魄力',
      caster_enrage: '自身激怒',
      caster_stealth: '自身隐身',
      caster_perception: '处于识破状态',
      caster_starshelter: '处于星之庇护状态',
      critical_hit_stack: '暴击叠加数',
      critical_hit_stack_12: '暴击叠加数',
      attack_skill_stack_3: '攻击叠加数',
      attack_skill_stack_5: '攻击叠加数',
      non_attack_skill_stack_3: '非攻击叠加数',
      non_attack_skill_stack_8: '非攻击叠加数',
      non_attack_skill_stack_10: '非攻击叠加数',
      turn_stack: '回合叠加数',
      turn_stack_3: '回合叠加数',
      dead_people: '死亡人数',
      enemy_counters: '敌人反击次数',
      highest_ally_attack: '我军最高攻击力',
      ally_atk_up: '目标我军攻击力增加',
      ally_atk_up_great: '目标我军攻击力增加 (大幅)',
      skill_tree_completed: '技能树满觉醒',
      s3_stack: '3技能叠加数',
      all_allies_fire: '全体我军火属性',
      exclusive_equipment_1: '专属装备 #1',
      exclusive_equipment_2: '专属装备 #2',
      exclusive_equipment_3: '专属装备 #3',
    },
    skills: {
      non_applicable: '无',
      s1: '1技能',
      s2: '2技能',
      s3: '3技能',
      s1_soulburn: '1技能 灵魂燃烧',
      s2_soulburn: '2技能 灵魂燃烧',
      s3_soulburn: '3技能 灵魂燃烧',
      mods: '技能倍率',
      att_rate: '基础倍率(Attack Rate)',
      power: '倍率修正值(Pow!)',
      mult: '条件收益倍率',
      flat: '固定值伤害倍率',
      critBoost: '暴击增伤系数',
      pen: '防御贯穿系数',
      detonation: '激爆',
      exEq: '专属装备',
      elemAdv: '属性克制',
      afterMathFormula: '行动后',
      afterMathDmg: '行动后追加伤害',
      extraDmg: '额外伤害',
      fixed: '固定伤害',
      custom: {
        caster_target_atk_diff: '{v}% 攻击力差距',
        caster_target_spd_diff: '{v}% 速度差距',
        caster_target_def_diff: '{v}% 防御力差距',
        all_fire: '{v}% 全体我军火属性',
        allies_buff: '+{v} 我军每个Buff数量',
        caster_defense: '{v}% 自身防御力',
        caster_left_hp_pc: '{v}% 自身剩余生命值百分比',
        caster_lost_hp: '{v}% 自身失去生命值',
        caster_lost_hp_pc: '{v}% 自身失去生命值百分比',
        caster_max_hp: '{v}% 自身最大生命值',
        caster_hp_pc_over_hp_threshold: '{v}% 自身生命值百分比[高于阈值]',
        caster_rage: '{v}% 愤怒套',
        caster_speed: '{v}% 自身速度',
        caster_hp_pc_under_hp_threshold: '{v}% 自身生命值百分比[低于阈值]',
        caster_vs_target_hp_diff: '自身与目标的生命值差距: {v}%/1000hp',
        dead_people: '{v}% 每个阵亡英雄',
        elemental_advantage: '{v}% 属性克制',
        per_crit_hit: '{v}% 每次暴击',
        per_target: '{v}% 每个目标',
        per_bleed: '{v}% 每个流血',
        per_fewer_target: '{v}% 每减少一个目标',
        per_focus: '{v}% 每格专注',
        per_stack: '{v}% 每叠加一次',
        per_target_debuff: '{v}% 每个Debuff',
        skill_tree: '技能树: {v}%',
        target_bleed: '目标流血: {v}%',
        target_debuff: '目标Debuff: {v}%',
        target_has_buff: '目标有Buff: {v}%',
        target_has_barrier: '目标有防护罩: {v}%',
        target_has_debuff: '目标有Debuff: {v}%',
        target_has_no_buff: '目标没有Buff: {v}%',
        target_has_silence: '目标沉默: {v}%',
        target_lost_hp_pc: '{v}% 目标失去生命值百分比',
        target_magic_nail: '魔法钉: {v}%',
        target_max_hp: '{v}% 目标最大生命值',
        target_speed: '{v}% 目标速度',
        target_hp_pc: '目标当前生命值: {v}%',
        target_hp: '{v}%目标当前生命值',
        under_threshold: '低于阈值: {v}%',
      }
    },
    info: {
      alencia_trample: '扼杀',
      aria_scaling: '注意：基于损失生命百分比的暴击伤害补偿可能不正确。但技能倍率是正确的.',
      lqc_s3_splash: 'S3 溅射伤害',
      ml_celine_nimble_sword: '快剑',
      s1_extra_attack: 'S1 追加攻击',
      s1_soulburn: 'S1 灵魂燃烧',
      s2_wave_2: 'S2 第二波',
      s2_wave_3: 'S2 第三波',
      s2_counter: 'S2 (反击)',
      sez_explosion: '溅射伤害',
      victorious_flag: '必须勾选属性克制才能看到效果, 对光暗英雄无效.',
      yoonryoung_slash: '闪光砍击'
      }
  }
};

const heroName = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return heroes[id].name;
  } else {
    return i18n[lang].heroes[id] || heroes[id].name;
  }
};

const heroNicknames = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  return i18n[lang].nicknames[id] || '';
};

const artifactName = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return artifacts[id] ? artifacts[id].name : 'No Artifact Proc';
  } else {
    return i18n[lang].artifacts[id || 'no_proc'] || artifacts[id].name;
  }
};

const formLabel = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return elements[id].label;
  } else {
    return i18n[lang].form[id] || elements[id].label;
  }
};

const skillLabel = (id, soulburn = false) => {
  const lang = document.getElementById('root').getAttribute('lang');
  if (lang === 'en') {
    return (id === 'non_applicable') ? 'n/a' : i18n[lang].skills[id] || id.toUpperCase() + (soulburn ? ' Soulburn' : '');
  } else {
    id = soulburn ? id+'_soulburn' : id;
    return i18n[lang].skills[id] || i18n['en'].skills[id] || id.toUpperCase();
  }
};

const compareSkillLabel = (id) => {
  const lang = document.getElementById('root').getAttribute('lang');
  const idSplit = id.split('_');
  id = idSplit[0];
  const extra = idSplit[1] || '';

  let display;
  if (lang === 'en') {
    display = id.toUpperCase();
  } else {
    display = i18n[lang].skills[id] || id.toUpperCase();
  }

  if (extra === 'sb') {
    display += '<i class="fas fa-fire"></i>';
  } else if (extra!== '') {
    display += '<i class="far fa-plus-square"></i>';
  }

  return display
};

const getSkillModTip = (tips) => {
  if (!tips) return '';

  const output = [];
  for (const key of Object.keys(tips)) {
    let lang = document.getElementById('root').getAttribute('lang');
    if (i18n[lang].skills['custom'] === undefined) lang = 'en';
    if (i18n[lang].skills['custom'][key] === undefined) lang = 'en';

    if (i18n[lang].skills['custom'][key] === undefined) return null;
    output.push((i18n[lang].skills['custom'][key]).replace('{v}', tips[key]));
  }

  return `(${output.join(', ')})`
}

const infoLabel = (key) => {
  let lang = document.getElementById('root').getAttribute('lang');
  if (i18n[lang].info === undefined) lang = 'en';

  return i18n[lang].info[key] || i18n['en'].info[key] || '';
}
